### ISSUE TITLE
Initial size could be specified in px (not just in %)

### ISSUE THREAD

**Issue by pedrogit** [nathancahill/Split.js#10]
So we could align initial panes sizes with other elements in the page.

**Comment by nathancahill** [comment]
I think this will look something like this:

```
Split(['one', 'two'], {
    sizes: ['30px', '560px'],
});
```

Might as well add support for any CSS value. The numeric values ([50, 50]) would still be interpreted as percentages for backwards compatibility.

**Comment by pedrogit** [comment]
Now how can I say:

Split(['one', 'two'], {
    sizes: ['30px', 'remaining of the container width'],
});

**Comment by nathancahill** [comment]
Seems like a handy use case. How does something like this look?

```
Split(['one', 'two'], {
    sizes: ['30px', None],
});
```

For setting both sides, something like this?

```
Split(['one', 'two', 'three'], {
    sizes: ['30px', None, '30px'],
});
```

**Comment by pedrogit** [comment]
What about 'auto' instead of ''None'?

**Comment by nathancahill** [comment]
Opps, right. Switching between writing Javascript and Python. 'auto' is much better.

**Comment by nathancahill** [comment]
As I'm working on this, I realized a problem with the 'px' sizes. When changing the browser window size, the sizes will not adjust like they do with calc(% - 5px). I think the desired behavior for 'auto' would be to automatically fill the space.

**Comment by pedrogit** [comment]
Right! Any progress?

**Comment by nathancahill** [comment]
Haven't come up with a clean way to do this, no.

**Comment by jolyonruss** [comment]
How about calculating the percentage at DOMReady, so if the sizes are set to ['30px', None, '30px'], inside an element that's 300px you could compute it down to ['10%', auto, '10%'], then when the window resizes everything still works...just a thought

**Comment by nathancahill** [comment]
Good idea @jolyonruss. Would 10%, 80%, 10% be the expected behavior though (fully flexible)? Or would you expect 30px, auto, 30px (fixed on the sides, flexible in the middle).

I'll take a swing at implementing the first.

**Comment by brumm** [comment]
Hey, might I also suggest using Flexbox for 'auto'?
That's the way it was done in atom: https://github.com/atom/atom/pull/5902

**Comment by nathancahill** [comment]
Support is added for flexbox in v1.2.0. I'd rather leave this feature out of the library and allow users to implement it by calculating the desired initial percentages beforehand.
