### ISSUE TITLE
The sub component minSize not work

### ISSUE THREAD

**Issue by easyfrog** [nathancahill/Split.js#101]
```html
// html
<div id="a">
</div>
<div id="b">
    <div id="c">
    </div>
    <div id="d">
    </div>
</div>

// javascript

Split(['#a', '#b'], {
    minSize: 0
});

Split(['#c', '#d'], {
    minSize: [0, '300px']
});
```

In the situation, when I drag the gutter (a,b), the minSize of #d while not work.

Here is the Demo:
https://jsfiddle.net/rfemnxec/6/

**Comment by nathancahill** [comment]
`minSize` is a number or array of numbers. Not a string like `'300px'`, you want to use `300` instead.
