### ISSUE TITLE
minSize property does not work

### ISSUE THREAD

**Issue by architagarwal** [nathancahill/Split.js#107]
Below is what my code looks like:

Split(['#a', '#b'], {
     sizes: [60, 40],
     minSize: [350, 200],
     gutterSize: 5
});

Split(['#c', '#d'], {
     sizes: [17, 83],
     minSize: [150, 200],
     gutterSize: 5
});

minSize property for #c and #d does not work. Also, I am able to drag the gutter to extreme ends of the window which tells me that the default minSize isn't working as well.

Any suggestions?

Thanks

**Comment by davidje13** [comment]
Could it be that you're hitting #72 ?

If your container is smaller than `ceil((150px + 5px / 2) / 17%) = 898px` then `c` will be initialised too small, causing it to hit that bug. As long as you initialise all sizes larger than the min size, it should behave OK (except for when the window itself resizes which I've raised a separate bug for).

**Comment by nathancahill** [comment]
Fixed in v1.5.0.
