### ISSUE TITLE
Resizing stalls if the mouse leaves the container

### ISSUE THREAD

**Issue by davidje13** [nathancahill/Split.js#111]
While dragging, if the mouse leaves the container / window the resize will stop until the mouse re-enters.

This is because although `mouseup` / `touchend` handlers are registered on the window, `mousemove` / `touchmove` are only registered on the parent element.

All drag events should be registered on the window so that dragging behaves naturally wherever the user moves the mouse.

Edit: Actually using `setCapture` / `setPointerCapture` on the gutter's `mousedown` would be better, since this would also make the cursor stick (even when the mouse leaves the window), removing the need to set cursors in multiple places. It would also prevent mouse interactions with other elements on the page (e.g. hover states) and might allow some of the selection prevention code to be reduced.

**Comment by nathancahill** [comment]
I hadn't heard of those two options (it looks like they aren't supported in Chrome). I'm ok with changing the `move` listeners to the window like the `end` listeners are. Can you submit a PR?
