### ISSUE TITLE
Some gutters are misaligned while dragging

### ISSUE THREAD

**Issue by davidje13** [nathancahill/Split.js#114]
Extracted from #112

The current behaviour intends that dragging a gutter will keep the centre of the gutter in line with the mouse pointer, but this is not always the case. For example, dragging the right-most bar in the bottom example of https://nathancahill.github.io/Split.js/ causes the gutter's right-edge to snap to the mouse.

I think it may be worth moving away from the current behaviour of detecting each segment's current size & position when dragging, and instead calculate where the divide ought to be based on the parent's size and position, and the current proportions. This would simplify the mathematics needed to account for gutters and would allow more flexible use cases (e.g. if a custom sizing function choses to inset all dimensions by 30px, or if something other than `border-box` is used in the CSS, it would make no difference to the engine).

This would be a rather large change so likely needs some thought on how it will interact with other existing features.

**Comment by adrianbj** [comment]
Any chance this has been fixed/improved by the new `gutterAlign` option in v1.5.3?
