### ISSUE TITLE
onDragEnd is triggered on mouse over

### ISSUE THREAD

**Issue by ozguruysal** [nathancahill/Split.js#12]
onDragEnd event is triggered unexpectedly on mouse over without even dragging the gutter. I've created an example [here](https://jsbin.com/kohahepawo/edit?html,js,console,output) to demonstrate the problem.

* Hover your mouse from div id one to div id two: dragEnd event for div three-four is triggered.
* Hover your mouse from div id two to outside of example div: dragEnd event for div one-two is triggered.
* Hover your mouse from div four to outside of example div: dragEnd event for both one-two and three-four is triggered.
* When you actually resize the vertical split panels, dragEnd is triggered for the parent panel too.
* Clicking inside the panels also triggers the dragEnd.

**Comment by nathancahill** [comment]
Very true, thanks for the great bug report. I'll look into this right away.

**Comment by nathancahill** [comment]
Thanks! New version released with the fix.

**Comment by ozguruysal** [comment]
Wow! That was lightning fast, thank you! :+1:
