### ISSUE TITLE
Hide Panel

### ISSUE THREAD

**Issue by fungl164** [nathancahill/Split.js#120]
I realize the collapse function exists, but I would really like to toggle a panel on/off (e.g. hide it)

In the meantime I created this little function to help with the illusion, but it's not quite the effect I'm looking for
```JS
function equalizeSizes ({exclude = []}) {
    let newSize = 100 / (elements.length - exclude.length)
    let newSizes = elements.map((p, idx) => {
        return exclude.indexOf(idx) == -1 ? newSize : 0
    })
    setSizes(newSizes)
}
...
```
To expose it, I use the following:
```JS
return {
  setSizes,
  getSizes() { ... },
  collapse(i) { ... },
  ...
  hide(i) {
        equalizeSizes.call(null,{exclude: [i]})
  },
  destroy,
  parent: parent,
  pairs: pairs
}
```

Am I missing something on how to accomplish temporarily removing/hiding an element from the split?  Any help would be greatly appreciated.  Many thanks!

**Comment by oskarkrawczyk** [comment]
I'm similarly trying to achieve something like this – hide a specific panel but not necessarily remove it from the split altogether

**Comment by long-lazuli** [comment]
I think we can manage this by adding a prop 'hidden' to each elements.  
Then each time one of those change, we recompose a list of pairs;

I did store this list of pairs in the PR #129 .
If this is merged, I can pass to this Issue.

**Comment by nathancahill** [comment]
I would destroy and recreate the split, hiding the specific panel in between. If you save the gutters and sizes, this is a noop and will result in no visual changes.

**Comment by abulka** [comment]
I think by 'destroy the split' @nathancahill means delete the gutter divs.  Here is a small snippet that ended up working for me:

```javascript
    toggler(e) {

      this.col3_visibility = !this.col3_visibility

      // https://github.com/nathancahill/split/issues/120
      // I would destroy and recreate the split, hiding the specific panel in between. 
      // If you save the gutters and sizes, this is a noop and will result in no visual changes.
      $('.gutter').remove()

      if (this.col3_visibility) {
        $('.c').show()
        Split(['.a', '.b', '.c'], {
          gutterSize: 5,
        });
      }
      else {
        $('.c').hide()
        Split(['.a', '.b'], {
          gutterSize: 5,
        });

      }
```
