### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by jameskleeh** [nathancahill/Split.js#123]
It has been quite a long time since the last release and there is a commit I'm interested in being able to use. Any chance you can cut a release?

**Comment by nikeee** [comment]
I'd like to get a new release, too. Espacially I'm interested in the TypeScript definitions. Currently, they are not shipped by the npm module.

**Comment by Hypenate** [comment]
Any news on this? 😄

**Comment by nikeee** [comment]
@erikjalevik why don't we put the awesome work of @icholy in this repository?

**Comment by burtonator** [comment]
Maybe a new maintainer is needed?  The existing one is probably slammed... or just fork and pick a new maintainer and/or until he has time to revisit?

Not trying to slam the existing maintainer btw..  this is a great project.

**Comment by nathancahill** [comment]
Published as 1.4.0. I'd be happy to add more people as maintainers. Please send me an email.
