### ISSUE TITLE
Disable gutter from being draggable

### ISSUE THREAD

**Issue by Corouna** [nathancahill/Split.js#124]
As titled. Is there a way to prevent the gutter from being draggable when i am putting a loader layout on either one of the splitted block? I want to disable the gutter dragging during loading and only enable back the drag when the loading is off.

**Comment by RussellJonesPersonal** [comment]
I suggest you use pointer-events:none.

In the example below, I've applied this to iPad sizes only, but you can do it yourself with or without media queries.

`@media only screen 
    and (min-device-width : 768px) 
    and (max-device-width : 1024px)  {
        .gutter {
            pointer-events: none;
        }
    }`

Hope that helps

**Comment by nathancahill** [comment]
You can destroy and recreate the split without any ill effects. This is preferred over blocking pointer events with CSS, although that works too.
