### ISSUE TITLE
Doesn't work if the parent <div> doesn't have an explicit height

### ISSUE THREAD

**Issue by nitinsurana** [nathancahill/Split.js#128]
This point is missing from the docs and the example page.

**Comment by bastiW** [comment]
did you find a solution? 

writing js code to update the heigt if you would like to have 100% height?

**Comment by bastiW** [comment]
There is a workaround

https://github.com/nathancahill/Split.js/issues/38

**Comment by eureka2** [comment]
my workaround:
```
	var container= document.getElementById('one').parentElement;
	container.style.height = container.offsetHeight + 'px';
	Split(['#one', '#two'], {
		sizes: [75, 25],
		cursor: 'col-resize'
	});
```

**Comment by nathancahill** [comment]
This is on the docs, in bold. You must set the CSS height if you're using floats.
