### ISSUE TITLE
Gutter cursor type issues while resizing

### ISSUE THREAD

**Issue by ozguruysal** [nathancahill/Split.js#13]
This is a minor issue I noticed. Please check this [demonstration](https://output.jsbin.com/fehaqiqono). It's also reproducible on your website.

Click and hold the first gutter from the left and move it left and right. Everything is smooth and perfect. You can see the cursor type remains the same.

Do the same on the second or third gutter. When you move the gutter to left, cursor type kind of flickers between `default` and `col-resize`. When you move it to right, `col-resize` is completely lost and it becomes `default`.

**Comment by nathancahill** [comment]
I see. I guess the columns should have a `.resizing` class while they are being dragged. Setting a cursor on that class would prevent the flickering.

**Comment by ozguruysal** [comment]
Looks like flickering happens on Chrome and IE but losing the cursor type while dragging right happens in all browsers.

The solution you suggest works well [here](https://jsbin.com/gamejuqusu/edit?html,css,js). But since first gutter is working perfectly, it's probably more than a CSS issue.

**Comment by ozguruysal** [comment]
I've just updated the example link. It was wrong. Btw, I can live with this current solution. Thank you very much for your help!

**Comment by nathancahill** [comment]
Just found a better fix. I added an option for setting the cursor when dragging.

**Comment by nathancahill** [comment]
Released in 0.4.6. The option would work like this for your example:

```js
Split(['one', 'two'], {
    cursor: 'col-resize'
});

**Comment by ozguruysal** [comment]
Excellent! Thank you.

**Comment by ozguruysal** [comment]
This issue is party back again. You can see on your website on the example with three vertical panels. While dragging the right gutter towards right cursor type changes to default.

**Comment by nathancahill** [comment]
Yep, I can re-create that.

**Comment by nathancahill** [comment]
Released in 1.0.5. Thanks!

**Comment by ozguruysal** [comment]
Thank you!
