### ISSUE TITLE
only resize pane, when drag end?

### ISSUE THREAD

**Issue by wangdingwei** [nathancahill/Split.js#132]
is it possible only resize pane, when drag end?

**Comment by everdimension** [comment]
I'd like to have this functionality, too.

I wish it was possibly to have an option to only move the _resizer_ and actually resize the pane when the user finishes moving the resizer. It would be great for projects with lots of perfomance-demanding rendering going on.

**Comment by nathancahill** [comment]
This is probably outside the scope of the project. However, you can use the `onDragStart` and `onDragEnd` callbacks to stop and start the perfomance-demanding rendering while dragging to the same effect.

**Comment by nathancahill** [comment]
Just added an option that might help you with this @everdimension. `dragInterval` limits dragging to a number of pixels at a time. So the performance-demanding rendering can be updated every 20-30px instead of every pixel.
