### ISSUE TITLE
Calling the whole module with 'this' does not work with browserify.

### ISSUE THREAD

**Issue by gsanta** [nathancahill/Split.js#14]
I have a problem using Split.js with my browserify-based project.
Browserify packages every module into a function call, so when Split.js is imported, the .call(this) at the end of the module won't refer anymore to the global window object, but it will be undefined.

Do you have a suggestion to this problem?

**Comment by nathancahill** [comment]
Ah, I see. I'll look into `this`.

**Comment by gsanta** [comment]
Thanks!

**Comment by gsanta** [comment]
I just passed temporarily 'window' instead of this, but maybe it would limit the possible usage environments.

**Comment by nathancahill** [comment]
So that last line would be `}).call(window);`?
Split.js isn't useful outside of the browser, so I'm fine with that.

**Comment by gsanta** [comment]
Yes, that would solve the problem, thanks!
