### ISSUE TITLE
Work with css grid

### ISSUE THREAD

**Issue by EgorOvechkin** [nathancahill/Split.js#142]
I glad to use this library.

Did somebody work with css grid ?
I am trying to use this library for it, but it doesn't work very well

ps: I need to change layout grid dynamically for resize right panel.
[my example](https://jsfiddle.net/egamegadrive16/gnL1at2k/2/)

**Comment by nathancahill** [comment]
Yes, Split.js is compatible with CSS grid. Look at the [Advanced](https://nathancahill.github.io/Split.js/#advanced) section.
