### ISSUE TITLE
Can't drag outside of gutters 

### ISSUE THREAD

**Issue by cyclonstep** [nathancahill/Split.js#145]
Hello I've been trying to use this library with react js as its framework. I found that whenever i wanted to drag the gutters in horizontal split, it can't be done when the mouse is outside of the gutters. Is there any workaround that can be done with this? Or is it a bug  ?

Thank you very much

**Comment by moritzvieli** [comment]
Hey there. I have exactly the same problem in Angular. Could you solve the problem meanwhile?

**Comment by moritzvieli** [comment]
Ah, got it in my case: The mouse events are attached to the parent element. Make sure, the parent element has a height, in case you use floating in the children. I had to add a clearfix to the parent:
https://stackoverflow.com/questions/12540436/height-of-parent-div-is-zero-even-if-it-has-child-with-finite-heights
