### ISSUE TITLE
Prevent gutter from being resizable

### ISSUE THREAD

**Issue by ericdevjs** [nathancahill/Split.js#146]
Hi,

I have 3 sections and I would like to prevent the gutter between section 1 and 2 from being draggable so that the section isn't resizable.

Thanks

**Comment by nathancahill** [comment]
Sounds like section 1 shouldn't be included in the split. Just "fake" a gutter element before 2 and 3:

`[  1  ]|[  2  ][  3  ]`

Your split is really just `[  2  ][  3  ]` then, `[  1  ]|` is static.
