### ISSUE TITLE
Possibility to use other selectors than id, when initializing Split.js.

### ISSUE THREAD

**Issue by gsanta** [nathancahill/Split.js#15]
Sorry, again :)

The fact that I have to give element ids, when initializing Split.js seems to be limiting. In many project, using ids are discouraged.
The getElemetById may could be replaced with querySelector, that would accept any kind of selector.

**Comment by nathancahill** [comment]
Yeah, I've been thinking about doing that. It's supported in all browsers that I care about. It would be a new major release though, because it would break backwards compatibility.

**Comment by gsanta** [comment]
Yes, that's right.
But it may would worth it, because the migration path is not difficult. (the user only has to put # in front of the ids)

**Comment by gsanta** [comment]
Until it's resolved, I use a fork.

**Comment by nathancahill** [comment]
Released in 1.0. Thanks!

**Comment by gsanta** [comment]
Thank you for the quick response!
