### ISSUE TITLE
yarn install fails due to open-collective

### ISSUE THREAD

**Issue by tecoholic** [nathancahill/Split.js#153]
I am using the [vue-split-panel](https://www.npmjs.com/package/vue-split-panel) in my project which depends on split.js. When I try to install the dependencies for the project I get the following error.

```
[4/4] 📃  Building fresh packages...
[1/6] ⡀ split.js
[2/6] ⡀ fsevents
[3/6] ⡀ cypress
[4/6] ⡀ nodent-runtime
error /Users/tecoholic/my_app/node_modules/split.js: Command failed.
Exit code: 127
Command: opencollective postinstall
Arguments:
```

I think the post install command of split.js is preventing the proper installation of the vue plugin.

**Comment by tecoholic** [comment]
I have opened the same issue in both the repositories. Sorry for spamming, but I am not sure if split.js or the vue plugin is the right place to report to.

**Comment by marekkaczkowski** [comment]
Fails on Jenkins even with `DISABLE_OPENCOLLECTIVE=true` as described on source repo https://github.com/opencollective/opencollective-postinstall

As @Robinfr said, this is due to wrong deps container so `DISABLE_OPENCOLLECTIVE` will not work.

```
> split.js@1.5.1 postinstall /tmp/workspace/***/node_modules/split.js
> opencollective postinstall

sh: opencollective: command not found
```

**Comment by nathancahill** [comment]
Ugh, sorry to push the bad build. Removed opencollective and published a new release. 1.5.2 is now on npm.
