### ISSUE TITLE
Keyboard shortcuts for resizing panes

### ISSUE THREAD

**Issue by adrianbj** [nathancahill/Split.js#154]
I have implemented for my own use and it works really nicely and also ties into the snapInterval option we've been discussing. I have only implementation for a single split (two panes) - I'm not sure how it would work for more. Any interest in incorporating something like this into the core codebase?

**Comment by nathancahill** [comment]
Yeah, probably best not in the core library. Are you using `getSizes` `setSizes` for resizing?

**Comment by adrianbj** [comment]
> Are you using getSizes setSizes for resizing?

Yes, I am using these but happy to keep this functionality working from outside of the core. I just thought it might be a useful addition for accessibility for those who can't use a mouse and rely solely on the keyboard.

I'll close this, but let me know if you change your mind and have any thoughts on how to handle more the one gutter.
