### ISSUE TITLE
Drawer functionality with pinning?

### ISSUE THREAD

**Issue by burtonator** [nathancahill/Split.js#158]
How hard would it be to implement this like an expand/collapse drawer?

http://react-component.github.io/m-drawer/examples/simple.html

With pinning and the existing functionality to resize it would be pretty awesome.

I guess one could hack this with a CSS transition and some way to hide the drawer again.

**Comment by nathancahill** [comment]
Should be possible with the current options. Might need some CSS trickery but doesn't look too complicated.
