### ISSUE TITLE
Problem when dragging split bar fast, it stops suddenly.

### ISSUE THREAD

**Issue by basilmusa** [nathancahill/Split.js#16]
Problem when dragging split bar fast, it stops suddenly.
I have to go back and move it slowly. This happens when the first and second divs contain lots of content. Happens under Chrome, Firefox and Internet Explorer.

**Comment by nathancahill** [comment]
Can you make a screen recording?

**Comment by nathancahill** [comment]
Is your mouse leaving the divs when you drag fast?

**Comment by nathancahill** [comment]
On Windows or Mac? Or at least share a jsfiddle that shows the problem.

**Comment by basilmusa** [comment]
It seems the problem takes place due to using an iframe in each div (left side and right side).
While dragging, once the mouse moves quickly inside an iframe, the mouse dragging stops.

**Comment by basilmusa** [comment]
Here's the jsfiddle link:
https://jsfiddle.net/zLr1L24y/
Remove the iframes from the html code and you get it working.

**Comment by nathancahill** [comment]
Fixed in version 1.0.1. Thanks!
