### ISSUE TITLE
Can't move gutter on touch

### ISSUE THREAD

**Issue by AndranikA** [nathancahill/Split.js#160]
I am able to move gutter on desktop using mouse, but on touch it doesn't work

**Comment by nathancahill** [comment]
We'll need more info. Device, browser, versions. What doesn't work? Are there any errors?

**Comment by AndranikA** [comment]
No errors, I have tested on iOS11.0.3(iphone6s, ipad air2), Android 8.0(Galaxy S7)

**Comment by nathancahill** [comment]
Thanks @AndranikA. Resolved this in 1.5.5 and published on npm.
