### ISSUE TITLE
Gutter width is not factored in to the minSize, leading to overflow

### ISSUE THREAD

**Issue by Autre31415** [nathancahill/Split.js#164]
I have a 3 pane horizontal view configured this way:

```
sizes: [10, 15, 75],
minSize: [0, 0, 0],
gutterSize: 2
```

I've added a button that when clicked "collapses" the first pane via `setSizes([0, 15, 85])`. (I did this instead of `collapse` so that I could allocate space to the last pane and not the second pane)

The problem is, when the first panel is collapsed, the third panel will get pushed down under the first two. This is happening because the size of the panels is calculated in an uneven way as follows:

Pane 1: `width: calc(10% - 1px)`
Pane 2: `width: calc(15% - 2px)`
Pane 3: `width: calc(75% - 1px)`

The width of the first gutter is being split in half across the first and last panes, which works perfectly fine when all 3 panes are in view, but once the first pane gets collapsed (Which renders the width of pane 1 to `calc(0% - 1px`) that half of that gutter isn't being subtracted from anywhere anymore which causes the series to add up to 1px more than 100%, and the third pane to get pushed down to a new line.

Looking over the API I see it's possible to interact with how the elements are sized via `elementStyle`, though I'm not sure if there's a supported way to interact with the sizing in a way that targets specific elements rather than the whole set (In my case the problem would be solved if pane 2 and 3 subtracted 2px each while the first subtracted none)

**Comment by nathancahill** [comment]
This sounds like a bug with how the 0% size is calculated. It should factor in the width of the gutter. Excellent bug report, updating the title to be more relevant.

**Comment by Autre31415** [comment]
It would be nice if the gutter was set to 0 (or hidden in some way) when its associated pane is collapsed to 0, but at the same time I can see how that might not jive with keeping the module behavior as simple and predictable as possible.

**Comment by nathancahill** [comment]
I just pushed a fix for the first part of the issue. It's not published on npm yet, but can you try the latest build in Github and see if that fixes the first part of the issue for you?

**Comment by Autre31415** [comment]
I just pulled down the latest master from github and here's the results:

Initial values:
Pane 1: 10% - 1px
Pane 2: 15% - 2px
Pane 3: 75% - 1px

After collapsing the first pane (Via `setSizes([0, 15, 85])`)
Pane 1: 0.114416% - 1px
Pane 2: 14.8856% - 2px
Pane 3: 85% - 1px

After expanding the first pane (Via `setSizes([10, 15, 75])`)
Pane 1: 10% - 1px
Pane 2: 14.8856% - 2px
Pane 3: 85% - 1px

Collapsing the first pane again:
Pane 1: 0.114416% - 1px
Pane 2: 14.7712% - 2px
Pane 3: 85% - 1px

This pattern repeats, with the second pane slowly shrinking by that 0.114416% figure after each collapse/expand cycle.

**Comment by nathancahill** [comment]
That's a good test, I'll add that to the test suite. Super helpful, I'll fix that issue.

**Comment by nathancahill** [comment]
Actually I'm not able to replicate this.. can you share which browser you're using and the dimensions/CSS of the divs and panes?

**Comment by Autre31415** [comment]
Oh I see the problem. In my current implementation I'm dynamically sizing the elements to preserve their relative sizes when the collapse happens like this:

```
let [pane1, pane2, pane3] = splitInstance.getSizes()

if (/* hide is toggled on */) {
  splitInstance.setSizes([0, pane2, pane3 - 10])
} else { /* when hide is toggled off */
  splitInstance.setSizes([10, pane2, pane3 + 10])
}
```

This worked previously, but now with the width being augmented dynamically upon collapse to account for the gutter I'm grabbing that new size and applying it inadvertently.

**Comment by nathancahill** [comment]
You can do some math to get the new value for `pane2`:

```js
} else { /* when hide is toggled off */
  splitInstance.setSizes([10, (100 - pane3 - 10), pane3])
}
```

**Comment by Autre31415** [comment]
Yeah changing up the math a bit handles the shrinking problem, but it is worth noting that since this update required a code change to account for with my silly edge case there could be other examples of `getSizes` usage across other apps in the wild that this could unintentionally effect as well. It might be worth considering to dynamically account for the gutter size by padding out the  `- #px` side of the CSS calc instead (if possible), since the value that `getSizes` returns is only the bare percentage pre calc.

Thanks for looking into this issue so quickly by the way! 😁  I'm glad my silly edge cases provided you with useful test cases

**Comment by nathancahill** [comment]
Definitely something to consider 👍
