### ISSUE TITLE
Stop dragging on leave parent

### ISSUE THREAD

**Issue by justdoo** [nathancahill/Split.js#17]
Looks like not so good decision.
`parent[addEventListener]('mouseleave', stopDragging.bind(pair))`

Any careless mouse move can break resizing.

**Comment by nathancahill** [comment]
Once your mouse leaves the parent, there's no way to listen for mouseup. Dragging would become stuck. I think this is the most user friendly way to solve it.

**Comment by DominoPivot** [comment]
I usually listen for mouseup on the whole page for this exact reason, unbinding the event when I don't need it. However, I prefer a disable on mouseleave than having bugs like I get with JSFiddle where the layout breaks if you're not careful.

**Comment by nathancahill** [comment]
Yeah, that would be the other option. I'm going to stick with mouseleave for now.

**Comment by justdoo** [comment]
I support **DominoPivot**. You can listen to `window`.
```javascript
window[addEventListener]('mouseup', handler);
```
*JSFiddle* has got a good example of splitters.
I'm pretty sure most people expect exactly that kind of behavior.

**Comment by nathancahill** [comment]
Ok, I see your point on JSFiddle. I'll switch to `window`

**Comment by nathancahill** [comment]
Released in 1.0.3. Thanks guys!

**Comment by justdoo** [comment]
Thank you, Nathan!

**Comment by justdoo** [comment]
Unfortunately, **three**-part demo is not working with new version.
I've tested it on copy of demo page ([nathancahill.github.io/Split.js](//nathancahill.github.io/Split.js))
Сlick on the **left** gutter, and it will "**stick**" to mouse.

**Comment by nathancahill** [comment]
You're 100% right. Will have a fix shortly.

**Comment by nathancahill** [comment]
Thanks again @justdoo. Fixed in 1.0.4.

**Comment by justdoo** [comment]
Works fine for now! Thanks.
