### ISSUE TITLE
option supply array of nodes, rather than selectors

### ISSUE THREAD

**Issue by davidmaxwaterman** [nathancahill/Split.js#20]
I find myself wanting to supply a list of nodes rather than css selectors. Is there an option? If not, is it plausible that it could be added?

**Comment by nathancahill** [comment]
Yeah, I think I'll add that, should be an easy fix.

**Comment by davidmaxwaterman** [comment]
Thanks.

I notice that document.querySelector() is used too, but that doesn't work in a shadow dom context. I'm hoping that is doesn't need to be used at all if the elements are passed in as a list of nodes.

```Uncaught TypeError: Cannot read property 'parentNode' of null...split.js:219```

(I'm also curious how you debug split.js since I can't even seem to place a breakpoint on that line, using chrome developer tools - is there a 'debug' version?)

**Comment by davidmaxwaterman** [comment]
To expand this a little, I am attempting to use Split.js to make a web component :

<https://github.com/01org/nlpljs/blob/mw-polymer-1.0-upgrade-2/example-app/app/content_push/cp-main.html#L39>

<https://github.com/01org/nlpljs/blob/mw-polymer-1.0-upgrade-2/example-app/app/content_push/cp-splitter.html>

I have some success, but I wonder if you could provide to guidance/advice, plus any thoughts.

**Comment by nathancahill** [comment]
Released in 1.0.5. Thanks!
