### ISSUE TITLE
dynamically remove split

### ISSUE THREAD

**Issue by adamjimenez** [nathancahill/Split.js#24]
I want to be able to dynamically create and remove splits. Obvs we can create splits but is there a way to dynamically remove splits also?

**Comment by nathancahill** [comment]
There isn't at the moment. What's the desired functionality? When the split is removed, it would remove the gutter and dragging?

**Comment by adamjimenez** [comment]
Yes,. essentially return everything to the state it was before the splits were added.

**Comment by nathancahill** [comment]
Right. Except for the sizes, the sizes would stay as they were last dragged?

**Comment by adamjimenez** [comment]
I'd remove the size attribs also but not a big deal either way as I would still need to do some other clean up.

**Comment by nathancahill** [comment]
Ok, I'll have it keep the latest size when it's removed because that seems the most user friendly.

**Comment by radpet** [comment]
When this functionality will be ready?

**Comment by ozguruysal** [comment]
I also need a similar functionality. I want users to be able turn off (then back on again) the panels that are shown on page load. Just hiding/revealing the panels via CSS classes is good enough for me (and probably the better way) but then the remaining active panels should be refreshed to fit nicely on the page again.

**Comment by rkraus1** [comment]
We were using splitter.js to allow the user to open a split screen, show some relevent data and then go back to full screen mode.  It would be very useful to remove the split.  I like being able to use your splitter because of the dragable sizing.

**Comment by chinchang** [comment]
@nathancahill Hey Nathan, is this feature being worked upon? If not, I would like to contribute here.

**Comment by nathancahill** [comment]
This is implemented in the latest release, v1.1.1.

```js
var instance = Split([], ...)
instance.destroy()
```

It removes the gutters and removes the CSS sizes that Split.js set on the elements. Please update to the latest version. Thanks!
