### ISSUE TITLE
scrollbar hiding grip when minsize=0

### ISSUE THREAD

**Issue by damien-git** [nathancahill/Split.js#25]
When a split pane has a right side with a 0 minimum width, the scrollbar will hide the grip, making it impossible to change the size again. Tested with Firefox 42.
A demo with a fully collapsible pane would be nice.

**Comment by nathancahill** [comment]
I'll have a fix and an example shortly. Thanks!

**Comment by PAEz** [comment]
This was because the movement limiter wasnt taking the gutter into account.
I added that and moved the limiter to adjust so other functions will also be limited (my updateOffset function) and not just the dragging.
http://plnkr.co/edit/ndQdCPAiZ7t6lDA32m4i?p=preview

**Comment by nathancahill** [comment]
This is fixed in the latest release.
