### ISSUE TITLE
Android

### ISSUE THREAD

**Issue by ThatTomPerson** [nathancahill/Split.js#26]
Issue with widths 
![screenshot_2015-12-10-14-52-08](https://cloud.githubusercontent.com/assets/1112472/11708001/e2b61ef6-9f4d-11e5-99df-acbabd7135c7.png)
I'll write more when I can get home and use a computer and dev tools to inspect what is happening 
I may also test with all of my other devices later

**Comment by nathancahill** [comment]
Thanks for the bug report! I really appreciate it (don't have Android devices to test on). Any additional information is helpful!

**Comment by nathancahill** [comment]
Fixed in v1.2.0.
