### ISSUE TITLE
New function for collapsing/expanding a split panel

### ISSUE THREAD

**Issue by streetcore** [nathancahill/Split.js#27]
I would like to see an enhancement to be able to collapse a split panel.
Essentially 'collapse()' would set the width (or height) to zero and the panel next to it to 100%.
A call to 'expand()' would bring back the gutter to the last state.
Collapse should also be available when min-size is not 0.

**Comment by nathancahill** [comment]
Yeah, right now nothing is returned from calling Split(). I think a Split instance should be returned, with methods like .destroy(), .collapse(n), .expand(n) where n is the zero indexed pane number.

**Comment by fabien** [comment]
+1

**Comment by gsanta** [comment]
+1

**Comment by tarr11** [comment]
+1

**Comment by devmondo** [comment]
+1 
this is really important it is blocking us now from using this cool plugin, as sometimes we really want to hide one pane completely or destroy the whole split

**Comment by glen-anderson** [comment]
+1

**Comment by PAEz** [comment]
One of the simpler ways to handle this is to make a click event for the splitter handle and let them handle it.
I wasnt sure the best way to do this (not great at dom specifics and still learning this code) so I just checked to see if you actually dragged and if not then on mouse/touch up, click.
Here's an example of the idea....
http://plnkr.co/edit/ndQdCPAiZ7t6lDA32m4i?p=preview

**Comment by argonautical** [comment]
+1

**Comment by nitinsurana** [comment]
+1

**Comment by nirsharonclick** [comment]
+1

**Comment by naivefun** [comment]
+2

**Comment by taufanardi** [comment]
+4 :+1:

**Comment by 2silver** [comment]
+1

**Comment by gsprs** [comment]
+1

**Comment by nathancahill** [comment]
Thanks everyone. I went ahead an implemented something similar, with a few more features in this release. The API now works like this:

```js
var instance = Split([], ...)
instance.collapse(0)
instance.collapse(1)
```
where `0` and `1` are the indexes for the elements in the split.

Additionally, it's possible to update the sizes now:
```js
instance.setSizes([10, 40, 50])
```
And destroy the the instance altogether:

```js
instance.destroy()
```
Docs are updated with the new API. Please update to the latest version, v1.1.1!
