### ISSUE TITLE
some questions...

### ISSUE THREAD

**Issue by davidmaxwaterman** [nathancahill/Split.js#28]
Hi,

Just wanted to ask a couple of questions :

<https://github.com/nathancahill/Split.js/blob/master/split.js#L265>

sets `isFirst` if `i` is 1. That's a little unobvious, but I can see later on that you're talking about *pairs* - ie the splitter always goes between two elements.

`isLast` makes sense either way.

However, lower down I see :

<https://github.com/nathancahill/Split.js/blob/master/split.js#L314>

I was wondering why you half the gutter size for i===0 instead of i==1 (not sure why == changed to == either - is there something I'm missing there?).

Hrm, I guess I'm just confused by the variable names? `isFirst` doesn't mean first element, but second element of first *pair*? `isLast` seems the same though.

I was originally trying to figure out why my splitter has broken with an upgrade to the latest version - I guess I still need to figure out what's going on. I currently have :

```
          Split(this.getContentChildren(), { sizes: [60, 40] });
```

Thanks for any insights.

Max.

**Comment by nathancahill** [comment]
Thanks Max. isFirst/isLast refer to the first and last pairs, instead of elements. Variables could be named better.
