### ISSUE TITLE
'npm install' fails at PhantomJS stage

### ISSUE THREAD

**Issue by HerrQ** [nathancahill/Split.js#33]
Preparing the test environment with 'npm install' fails at the PhantomJS stage on Ubuntu 14.04:

```
npm ERR! Linux 3.19.0-47-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.2.6
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE

npm ERR! phantomjs2@2.0.0 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the phantomjs2@2.0.0 install script 'node install.js'.
npm ERR! This is most likely a problem with the phantomjs2 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls phantomjs2
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/q/Split.js/npm-debug.log
```

Log file: [npm-debug.zip](https://github.com/nathancahill/Split.js/files/102989/npm-debug.zip)

**Comment by DiscoNova** [comment]
PhantomJS is not a direct dependency of `Split.js` ... probably this issue should be targeted towards `nathancahill/grunt-contrib-jasmine` or `nathancahill/phantomjs2` instead?

However... this looks like it may have something to do with your issue *(from the readme of phantomjs2)* ... but I am just guessing.

> **I'm on Debian or Ubuntu, and the installer failed because it couldn't find `node`**
> 
>  Some Linux distros tried to rename `node` to `nodejs` due to a package conflict. This is a non-portable change, and we do not try to support this. The [official documentation](https://github.com/joyent/node/wiki/Installing-Node.js-via-package-manager#ubuntu-mint-elementary-os) recommends that you symlink `node` to `nodejs` on those platforms, or many NodeJS programs won't work properly.

**Comment by nathancahill** [comment]
PhantomJS 2 isn't well supported yet in the npm ecosystem. See https://github.com/nathancahill/Split.js/issues/8#issuecomment-148822145 when I added tests. It's a rabbit hole. There's also a long thread here on PhantomJS 2 support: https://github.com/travis-ci/travis-ci/issues/3225

Would you mind opening an issue on https://github.com/nathancahill/phantomjs2?
