### ISSUE TITLE
api to set width

### ISSUE THREAD

**Issue by naivefun** [nathancahill/Split.js#34]
is there an api to call to show/hide certain div? would be nice for shortcut button.

**Comment by nathancahill** [comment]
There isn't an API to do that, but I'll add it to the roadmap.

**Comment by nathancahill** [comment]
Thanks, I went ahead an implemented this, with a few more features in this release. The API now works like this:

```js
var instance = Split([], ...)
instance.collapse(0)
instance.collapse(1)
```
where `0` and `1` are the indexes for the elements in the split.

Additionally, it's possible to update the sizes now:
```js
instance.setSizes([10, 40, 50])
```
Docs are updated with the new API. Please update to the latest version, v1.1.1.
