### ISSUE TITLE
Callback Parameters

### ISSUE THREAD

**Issue by kstover** [nathancahill/Split.js#35]
Would it be possible to get the current sizes of the split pairs in the callbacks? I need to update an external source on dragend.

**Comment by nathancahill** [comment]
Yes, this is doable. I'll add it to the next release.

**Comment by kstover** [comment]
Thanks! I've modified my local copy to add "this" as the passed variable. Seems to work well in my use-case.

**Comment by kstover** [comment]
Oops. I meant to add that I've also passed "this" to the dragStart function as well.

**Comment by nathancahill** [comment]
You can use the new API `getSizes()` to get the current sizes in the callback.
