### ISSUE TITLE
wrapping with a div breaks the layout

### ISSUE THREAD

**Issue by davdtm** [nathancahill/Split.js#36]
By wrapping the page within a div (open it just after body and close it just before /body) the layout seems broken. Is there any workaround for this?

thanks

Davide

**Comment by nathancahill** [comment]
What are you trying to accomplish?

**Comment by davdtm** [comment]
Hi Nathan. Just to give you an example, let's say I want to define two DIV containers, one is the true container of my contents (with id='page_contents', say) and the other is a footer (with id='footer'). Let's say I want to apply the split.js layout ONLY on all DIVs contained within #page_contents, so that anything inside #footer should not be affected. It seems this does not work.
Your script works beautifully but it cannot be arbitrarily applied to just "some DIVs" in the page (and their contents, of course). As other test, I've taken the example provided by the demo and I've just wrapped the body content within a DIV (that is, I've added a DIV to wrap anything inside the body tag) and this was sufficient to break the layout. This sounds weird to me and looks like a bug. At least, my impression is that this reduces a lot the script flexibility.

regards

Davide

**Comment by rsbondi** [comment]
[works](http://plnkr.co/edit/8BcA6A?p=preview)

[does not work](http://plnkr.co/edit/GBPwYG?p=preview)

the second example is the first one uncommented.

**Comment by ozguruysal** [comment]
@rsbondi in your [first example](http://plnkr.co/edit/8BcA6A?p=preview) it works because you set a height property of 100% in your css for the wrapper element that is `body`, however for the [second example](http://plnkr.co/edit/GBPwYG?p=preview) there is no height set for `content` which is the the wrapper element in this case.

Add this to your `style.css` and second example works too:
```css
.content {
  height: 100%;
}
```

Likewise remove this from the first example and it also fails:
```css
html, body {
  height: 100%;
}
```

You always need to set a minimum height for the wrapper element of the split containers.

**Comment by davdtm** [comment]
ozguruysal, thanks for highlighting this! Just a question: in the documentation there's this statement "the only CSS Split.js sets is the widths or heights of the elements. Everything else is left up to you". I didn't find any other reference nor comment about the fact that it's mandatory to set the height of the split container and from that sentence it's not obvious. It seems to me that such a strong requirement (as any other strong one, if known) should deserve to be explicitly stated. 

thanks

Davide

**Comment by rsbondi** [comment]
@ozguruysal that pushes the footer off the page.  I have resolved [here](http://plnkr.co/edit/kZ33dO?p=preview).  I needed to add `position:relative` to the flex container and wrap the split section with 
```css
.split-wrap {
  position: absolute;
  height: 100%;
  width: 100%;
}
```

**Comment by ozguruysal** [comment]
@rsbondi sure, thanks for sharing your solution.
