### ISSUE TITLE
be cool if someone added an Angular2 wrapper...

### ISSUE THREAD

**Issue by born2net** [nathancahill/Split.js#37]
be cool if someone added an Angular2 wrapper...
if added, I would add this to http://ng2.javascriptninja.io
Regards,

Sean

**Comment by bertrandg** [comment]
@born2net I'm currently working on an ng2 wrapper if you're still interested:
https://bertrandg.github.io/ng2-split/

**Comment by born2net** [comment]
I am tx !!!
