### ISSUE TITLE
Height 100%

### ISSUE THREAD

**Issue by AlbatiQue** [nathancahill/Split.js#38]
Hey I'm trying to make the split items full height of the browser window minus the height of the navbar.
But when setting the height to for example 100% . The split view functionality does not work anymore.
How can I achieve this?

Thanks for the help!

**Comment by billcsharp** [comment]
I'd prefer a CSS answer but I achieved this with JavaScript. Using jQuery you can hook into the window resize event, and then use the height of the window to set the height of the parent pane container.

**Comment by ozguruysal** [comment]
You can try CSS3 `vh` unit. 1vh = 1% of viewport height. So if you want 100% viewport height minus the height of the navbar (let's assume your navbar height is 70px), you can set the height like this:

```
height: calc(100vh - 70px);
```
