### ISSUE TITLE
Angular compatibility

### ISSUE THREAD

**Issue by JuanCaicedo** [nathancahill/Split.js#41]
Hi there! I was just wondering if anyone has built anything integrating this with Angular. My idea is that there would be a `split-area` directive that you could use in your app to make divs inside of it automatically split-able. I'm playing around with it with @CCole and having some trouble getting a minimal example working

**Comment by JuanCaicedo** [comment]
There was an angular2 related issue as well #37

**Comment by nathancahill** [comment]
Outside the scope of the project.
