### ISSUE TITLE
Doesn't work if the parent has reversed flex-direction

### ISSUE THREAD

**Issue by chinchang** [nathancahill/Split.js#43]
If parent has `flex-direction` as `row-reverse`, the sequence of the elements in the DOM doesn't actually reflect the visual sequence and hence the library logic breaks and causes unintended resizing.

**Comment by nathancahill** [comment]
Thanks @chinchang! Added support for `row-reverse` in 1.1.4.

**Comment by chinchang** [comment]
awesome 👍
