### ISSUE TITLE
Missing changelog

### ISSUE THREAD

**Issue by Fidel90** [nathancahill/Split.js#52]
Hi Nathan,

I'm unable to find a changelog. As I'm willing to use your library in a production app, I need to know what changes happend since the last version to verify if I have to upgrade and what could go wrong if I do. It would be very appreciated if you could add a changelog/history. Thanks :+1:

**Comment by DiscoNova** [comment]
`git log <sha-for-release-1> <sha-for-release2>`

**Comment by ozguruysal** [comment]
They are also available on every release https://github.com/nathancahill/Split.js/releases

**Comment by nathancahill** [comment]
Besides the releases page, Split.js follows semver, with minor versions used for bug fixes and non-breaking changes. Major versions (only [1.0.0](https://github.com/nathancahill/Split.js/releases/tag/v1.0.0) has been released) have a list of Breaking Changes in the release notes.
