### ISSUE TITLE
The simplest example

### ISSUE THREAD

**Issue by greggman** [nathancahill/Split.js#57]
It put what seems to be the simplest example [here](https://jsfiddle.net/greggman/aqpc4t4f/) 

It's just this

```
<div>
        <div id="left"> foo </div>
        <div id="right"> bar </div>
</div>
<script src="https://nathancahill.github.io/Split.js/split.js"></script>
<script>
Split(["#left", "#right"], {});
</script>
```

plus the CSS copied from the demo page docs

and yet nothing happens. I'm probably doing something completely stupid and it's staring me in the face.

**Comment by keyscores** [comment]
@nathancahill  can you take a look at this jsfiddle: https://jsfiddle.net/etwauo25/ 

It's unclear how to get the gutter to initialize. Thanks in advance.

**Comment by nathancahill** [comment]
You have to set the height of the elements. Split.js does not do that for you. Updated Readme to clarify that.

**Comment by keyscores** [comment]
@nathancahill  thanks for the quick response. I'm still not getting any results on this jsfiddle with your new examples. See the new example here: https://jsfiddle.net/etwauo25/2/

Could you possibly link a working JS fiddle to the docs? Thanks in advance!

**Comment by nathancahill** [comment]
Read the docs. You still aren't setting the height: https://jsfiddle.net/etwauo25/3/

**Comment by keyscores** [comment]
Ok thanks. If you could update the quickstart example in the readme, it would make it clear which div needs height.
Also some css in the quickstart would be helpful. Thanks for a nice component.

**Comment by gmlewis** [comment]
Is https://jsfiddle.net/etwauo25/3/ supposed to be a working example?
All I'm seeing in the window is `SETTHEHEIGHT` with no draggable split bars.

**Comment by vasyl-shumskyi** [comment]
Thanks for a great module. Working jsfiddle would be much appreciated in examples.

**Comment by Wyzix33** [comment]
It's simple, just set a height to the container and display flex and specify initial width on splitjs initialization
https://jsfiddle.net/1pq9rbsy/1/
