### ISSUE TITLE
API for moving the split programatically

### ISSUE THREAD

**Issue by gsanta** [nathancahill/Split.js#58]
I need to manipulate the split position programmatically, it would be useful if the Split function would return an object, that can contain API functions like this.

I solved it temporarily like this:

```
Split = function (ids, options) {
...
    return {
        resize: function(size) {
            adjust.call(pair, size);

            if (options.onDrag) {
                options.onDrag()
            }
        }
    }
}
```

**Comment by nathancahill** [comment]
Thanks @gsanta! I went ahead an implemented something similar, with a few more features in this release. The API now works like this:

```js
instance.setSizes([10, 40, 50])
```
Additionally, it's possible to collapse specific elements:

```js
var instance = Split([], ...)
instance.collapse(0)
instance.collapse(1)
```
where `0` and `1` are the indexes for the elements in the split.

Cheers!
