### ISSUE TITLE
Cannot use if just vertical panes are set (unless a container with height attribute is present)

### ISSUE THREAD

**Issue by ismail44** [nathancahill/Split.js#59]
I had a use-case that dictated I only use a vertical splitter to split two rows. My code looked like this:

`<div id="pane_1" class="split">Pane 1</div><div id="pane_2" class="split">`

`Split(["#pane_1", "#page_2"], {direction: vertical});`

The calculation for the height attribute for each of the panes was being properly set, however, the actually CSS calculation wasn't working because it didn't have any reference. At least that's the best I can guess... I solved it by wrapping my panes with an outer element (a div in my case) with the height explicitly set. 

I don't think this is a "bug" in this code, just an anomaly.

**Comment by nathancahill** [comment]
Yes, the parent must have it's height specified or implied in CSS.
