### ISSUE TITLE
How to use expand / collapse in tlozynsky fork

### ISSUE THREAD

**Issue by amnevins** [nathancahill/Split.js#60]
Possible to update readme or add comments for how to use the expand/collapse functionality in tlozynskyy fork.  It would definitely make this package more super awesome.  Thanks.

**Comment by nathancahill** [comment]
I went ahead an implemented something similar, with a few more features in this release. The API now works like this:

```js
var instance = Split([], ...)
instance.collapse(0)
instance.collapse(1)
```
where `0` and `1` are the indexes for the elements in the split.

Additionally, it's possible to update the sizes now:
```js
instance.setSizes([10, 40, 50])
```
Docs are updated with the new API. Please update to the latest version.
