### ISSUE TITLE
API to get the current sizes

### ISSUE THREAD

**Issue by cristianobarros** [nathancahill/Split.js#67]
Would it be possible to add a method to get the current sizes of the split panels?
I'm building an Electron app, and when the user closes it, I want to save these sizes. This way, when the app starts again, I'll pass the previosly saved sizes as parameter to the constructor.

**Comment by nathancahill** [comment]
Thanks! `getSizes()` added in 1.1.2 and published on npm.

**Comment by cristianobarros** [comment]
Thank you so much! I updated the version to use the new method, and it worked perfectly!
