### ISSUE TITLE
Saving state issue

### ISSUE THREAD

**Issue by Wyzix33** [nathancahill/Split.js#69]
Hi, i tried to apply saving state to your jsfiddle.html example and after i change size and refresh it breaks, See this jsfiddle i made:

[https://jsfiddle.net/wyzixg/kw3mmt6o/1/](url)

press run change vertical size and press run again, if i clear localStorage it works, i think it's because  localStorage returns a string and sizes argument must be array, maybe a check would solve the problem

```
var sizes = localStorage.getItem('split-sizes') || [50, 50];
if(typeof sizes === 'string') sizes= sizes.split(",").map(Number);
```
or you could do it inside Split.js

Thanks, and great work with Split.js

**Comment by nathancahill** [comment]
Ah, forgot that localStorage uses strings. Updating the example.
