### ISSUE TITLE
Calling split on three elements doesn't use percentages

### ISSUE THREAD

**Issue by behr328** [nathancahill/Split.js#71]
Consider the following split. Doing this causes the div calculations to be hardcoded in pixels rather than in percentages meaning that the split isn't adaptive when the page is resized. The percentage are applied when working with only a two div split but breaks when working with a three div split.

Split(["#one", "#two", "#three"], {
        gutterSize: 3,
        sizes: [70, 20, 10],
        direction: "vertical"
});

**Comment by nathancahill** [comment]
Are you using the latest version? This should be calculated in percentages. If not, can you put that in a JSFiddle?

**Comment by nathancahill** [comment]
Closing for now.
