### ISSUE TITLE
Using "max-height" in the css attributes of "api" will make your horizontal split useless

### ISSUE THREAD

**Issue by sanleong** [nathancahill/Split.js#75]
If I try to put a max-height to the css attributes like the example below, the results of my split panels will come out but the divider bar doesn't appear and you can't change the width of the panels.
`.api {
    max-height: 600px;
    border: 1px solid #ddd;
    border-radius: 4px;
  }`
![image](https://cloud.githubusercontent.com/assets/1580031/22981118/7f5ed1ce-f369-11e6-8178-dda73e1f813c.png)

**Comment by nathancahill** [comment]
Yes, you need to set the actual height of the gutters, or set their height to 100% if they are inside an element with height. Setting max-height is not enough.
