### ISSUE TITLE
Typescript definitions

### ISSUE THREAD

**Issue by sbusch99** [nathancahill/Split.js#77]
I'm having trouble using Split.js with angular-cli, TypeScript and webpack. I create one file that has below but that's not sufficient. 

Thanks you.

**export declare function Split(ids: string[], sizing: any): void;**

**Comment by nathancahill** [comment]
Hmm, I haven't used Split.js with Typescript, so I'm not sure what it would require. If anyone wants to write a definition, or has one already I'd accept a PR.

**Comment by dungahk** [comment]
I've followed this guide to use Split.js in my Angular project: https://github.com/angular/angular-cli/wiki/stories-third-party-lib

It works perfectly.

**Comment by searene** [comment]
I just wrote one and it seemed working.

```javascript
/* use it like this:
 
import Split = require('split.js');

Split(['#a', '#b'], {
  gutterSize: 8,
  cursor: 'col-resize'
});
*/
declare module 'split.js' {
    interface SplitOptions {
        sizes?: number[];
        minSize?: number[] | number;
        gutterSize?: number;
        snapOffset?: number;
        direction?: "horizontal" | "vertical";
        cursor?: "col-resize" | "row-resize";
        gutter?: (index: number, direction: string) => HTMLElement;
        elementStyle?: (dimension: number, elementSize: number, gutterSize: number) => any;
        gutterStyle?: (dimension: number, gutterSize: number) => any;
        onDrag?: ()  => void;
        onDragStart?: () => void;
        onDragEnd?: () => void;
    }

    interface SplitObject {
        setSizes: (sizes: number[]) => void;
        getSizes: () => number[];
        collapse: (index: number) => void;
        destroy: () => void;
    }

    function Split(elements: HTMLElement | string[], options?: SplitOptions): void;

    export = Split;
}
```

**Comment by nathancahill** [comment]
Want to submit that file as a PR?

**Comment by raindog9** [comment]
@searene could you provide a bit more guidance? (sorry I'm new to typescript and modules) ...

I ran the "npm install --save split.js" and have added the "import Split = require('split.js');" into my .ts file
It compiles ok but at runtime there is an error because the http request is trying to get the file from location "/split.js" (instead of "/node_modules/split.js/split.js") and so causes a 404 error.
I've tried with and without your declare definition in a split.d.ts file located in my source directory and in "node_modules/split.js/" but always the 404 error.

**Comment by searene** [comment]
@nathancahill Sorry I've been busy recently, I just pulled a request about the typescript definition, you can check it out.

@raindog9 For now you can download the typescript definition from [here](https://raw.githubusercontent.com/searene/Split.js/2bb87f411c5c67c3c4fe4b85c89761a743affff2/index.d.ts) as a file `index.d.ts`, and copy the file into `node_modules/split.js/index.d.ts`, it should work. If you don't want to spoil your `node_modules` directory, you can copy the file as `split.js.d.ts` and put it in the same directory as your ts file, which invokes Split.js APIs.

**Comment by raindog9** [comment]
@searene Thanks - I had missed the ".js" part when naming the "split.js.d.ts" file.

Also I found that I had to add a map item to systemjs.config.js to solve the 404
`map: {
      // our app is within the app folder
      app: 'app',
      ...
      'split.js': 'npm:split.js/split.js'
    },`

**Comment by StNekroman** [comment]
`export = Split;` - export for idiots.

Should be `export default Split`
