### ISSUE TITLE
Problems if the panels to split are contained in another div

### ISSUE THREAD

**Issue by evolucionapp** [nathancahill/Split.js#79]
I am trying to use this attractive library, but I found a problem when I use it on divs that are inside another (already existing) div.

This is the working example I built first: [https://jsfiddle.net/xqLptjyz/2/](https://jsfiddle.net/xqLptjyz/2/). As you can see, the split control is displayed and it works:

![working](https://cloud.githubusercontent.com/assets/763974/24934607/32875db8-1ee2-11e7-864d-37b63b5f1892.gif)

The following example is where I simply wrap the same working HTML in the previous example with a simple div. In this case, the split library does not seem to work: [https://jsfiddle.net/xqLptjyz/1/](https://jsfiddle.net/xqLptjyz/1/)

![capture000222](https://cloud.githubusercontent.com/assets/763974/24934673/9f338054-1ee2-11e7-9426-0434f2d6b893.png)

In general I used simple code, so I don't see any special mistake in my code. Please let me know if there is any problem in my code, or if this is actually a problem with the Split.js library.

**Comment by nathancahill** [comment]
For a horizontal split like that, Split only controls the widths and doesn't touch the height. So you want to make sure that the height is being set by the CSS. If you include this in the CSS in the JSFiddle it should work:

```
html,
body,
#tabs_container,
#document_viewer_container,
.content {
    height: 100%;
  }
```
