### ISSUE TITLE
Sizes not adding to 100%

### ISSUE THREAD

**Issue by Wyzix33** [nathancahill/Split.js#82]
Hi, i just noticed that after i make a resize and save the values of 2 splited elements, after i reaply the sizes next time they are not full width and a little space si left in the right side, for example i have this sizes saved after one drag:
81.41248686974791,18.386456144957982
witch is 99.79894301470589, and i think the space is just about 0.2%
Can this be solved by adding the missing width till 100% to last element or is it a internal bug?
I also noticed this in your example at the bottom, first Get Sizes is  [50, 25, 25] and after i drag one i get 
[45.14939979123173, 29.446111691022963, 25] witch is not adding up to 100, it's 99.59551148225469, i think in your example the gap is bigger (0.4%)  because the container is smaller

Here is a screenshot with the difference, before loading the elements with the saved sizes, and after:

![split](https://cloud.githubusercontent.com/assets/13553412/26559129/58e61428-44b6-11e7-98e0-b47215799d3c.jpg)

Thanks for your time and good job with this library!

**Comment by nathancahill** [comment]
Thanks for the bug report, I'm looking in to it.

**Comment by Wyzix33** [comment]
Ok, glad to hear that, also, if i repeat the steps that gap is getting larger and larger... each time gaining .2% or more in width.

**Comment by nathancahill** [comment]
Would you mind testing the latest build in the repo, this file: https://github.com/nathancahill/Split.js/blob/master/split.js or if you're including it via CDN: https://rawgit.com/nathancahill/Split.js/master/split.js

**Comment by Wyzix33** [comment]
Hi, it's still happening...

**Comment by Wyzix33** [comment]
Disregard my last comment, it's fixed now  👍

**Comment by nathancahill** [comment]
Both are updated. Released as 1.3.5
