### ISSUE TITLE
Window resize does not respect minWidth settings

### ISSUE THREAD

**Issue by GeoFounders** [nathancahill/Split.js#87]
I am unable to get the window resize to respect the Split.js minWidth settings. Instead, the panels resize proportionally past the minWidth until you drag the gutter, in which it pops back to the minWidth.

**Comment by nathancahill** [comment]
Split.js does not attach any window event listeners, but you could add your own, and call:

```
split.setSizes(split.getSizes())
```

which would update the sizes to respect any `minSize`.

**Comment by GeoFounders** [comment]
Thanks for the help! I was able to force a minWidth for the left panel on window resize using the following code:

```
$(window).resize(function(){
    var panelSizes = split.getSizes();
    if (((panelSizes[0] * 0.01) * winWidth)  < 390) {
        var newLeft = ((390 / winWidth) * 100);
        split.setSizes([newLeft, (100 - newLeft)]);
    }
});
```

**Comment by nathancahill** [comment]
Hmm, setSizes/getSizes didn't work directly? That would be a bug. Because setSizes should respect the minSize, without having to do further calculation.

**Comment by GeoFounders** [comment]
Unfortunately it didn't work directly on Safari and Chrome on Mac. It would maintain the panel ratio when the window resizes and would maintain that ratio past the minWidth. I'll see if I can help correct the issue later this week when I have more time. Other than that, the library works great! Nice and simple!

**Comment by nino-vrijman** [comment]
@nathancahill This issue also exists on Split Grid, is there 

> Split.js does not attach any window event listeners, but you could add your own, and call:
> 
> ```
> split.setSizes(split.getSizes())
> ```
> 
> which would update the sizes to respect any `minSize`.

@nathancahill This issue also exists on Split Grid, I can't seem to find a simple solution for Split Grid like the one above for Split.js.
