### ISSUE TITLE
Split a flex item

### ISSUE THREAD

**Issue by racerhere** [nathancahill/Split.js#88]
I have a flex item
```
<div style="display: flex">
  <div style="flex-basis: 1 1 auto">
    <!-- some content -->
  </div>
  <div style="flex-basis: 1 1 auto">
    <!-- I need to split this div vertically into two equal parts -->
  </div>
</div>
```
How do I setup my split configuration? Any help is appreciated.

**Comment by nathancahill** [comment]
The README describes this here: https://github.com/nathancahill/Split.js#flexbox

**Comment by racerhere** [comment]
Thanks for the prompt reply, @nathancahill. Please take a look at this Plunker: [https://plnkr.co/edit/DekbBbllTZvgXW6ZRv63?p=preview](https://plnkr.co/edit/DekbBbllTZvgXW6ZRv63?p=preview).

I am trying to have a persistent unsplit content (25% on left side) and trying to vertically split the remaining 75% on the right. I do not want to split the left and right side.

Any help is appreciated.

**Comment by nathancahill** [comment]
Sorry, this issue tracker is for bug reports. I offer support here: https://github.com/nathancahill/Split.js/wiki/Split.js-Support
