### ISSUE TITLE
The initial size can be smaller than the specified minSize

### ISSUE THREAD

**Issue by pedrogit** [nathancahill/Split.js#9]
If I split like this:

Split(['lileftpanel', 'rightpanel'], {
        sizes: [5, 95],
        minSize: [200, 200]
    });

and my container is 600px wide, the initial size of the first pane get set to 5% of 600 which is 30px which is smaller than the minsize I set. minSize should overwrite the initial size if it is bigger.

Otherwise it would be nice to be able to specify the initial sizes in pixel (not just in percentage) so I can align panes with other elements located on top of them.

**Comment by nathancahill** [comment]
That makes sense. I'll have a fix for the minSize overriding the initial size shortly. I'll think about specifying values as pixels. Mind opening another issue for that?
