### ISSUE TITLE
Add max / min toggle

### ISSUE THREAD

**Issue by data-handler** [nathancahill/Split.js#90]
Hi,

Thanks so much for this plug-in.

This may have been suggested / considered already, but would it be possible to add a button to toggle the split between min and max size?

**Comment by nathancahill** [comment]
I'd suggest using the [setSizes](https://github.com/nathancahill/Split.js#setsizes) API, and attaching event listeners to your own button.

**Comment by data-handler** [comment]
Wow. Thanks a lot
