### ISSUE TITLE
Unable to resize panels when size set with CSS strings

### ISSUE THREAD

**Issue by manndave** [nathancahill/Split.js#91]
First, great plugin.  Thanks for it.

The only problem I'm having, which could very possibly be me misunderstanding how to make it work is this:  if I set my sizes using CSS string like this: `sizes: ['calc(100% - 30px)', '30px']`, it shows up correctly on the screen (bottom panel is 30 px high, top panel takes up the rest of the screen), but I can't drag to resize the panes.  I get the cursor change when I mouse-over, but when I click & drag nothing happens and no errors in the console.

Here's my code:
```
Split(['#top-panel', '#bottom-panel'], {
        direction: 'vertical',
        gutterSize: 6,
        sizes: ['calc(100% - 30px)', '30px'],
        cursor: 'row-resize'
});
```
And my HTML:
```
<div id="top-panel" class="split content">
    1
</div>
<div id="bottom-panel" class="split content">                   
    2
</div>
```

Browser is Chromium in Electron.

Thanks.

**Comment by manndave** [comment]
ANy thoughts?  Thx.

**Comment by nathancahill** [comment]
Looking in to this. As a temporary work around, is it possible to calculate 30px as a percentage of the window height? And then do `sizes: [100 - 5, 5]` (if 30px was 5% of the window height).

**Comment by manndave** [comment]
Thanks, @nathancahill.  I'll give that a try and let you know.

Dave

**Comment by dukewan** [comment]
Hi, I have the same issue for `v1.3.5`. It used to work for me at `v1.1.1`. I temporarily roll back to `v1.1.1` and it works fine for me. @nathancahill @manndave

**Comment by ambischof** [comment]
I think I have the same issue. This is my initialization: 
```
this._split = Split([this.$('> div > .list-panel')[0], this.$('> div > .content-panel')[0]], {
	sizes: ["300px", "auto"],
	minSize: 200,
	elementStyle: function(dim, size, gutterSize){
		if (!_.isString(size)) size = size + '%';
		return {
			'flex-basis': 'calc(' + size + ' - ' + gutterSize + 'px)',
			'-webkit-flex-basis': 'calc(' + size + ' - ' + gutterSize + 'px)'
		};
	},
	gutterSize: 5
});
```
As I've traced it back, it seems to be the [adjust function](https://github.com/nathancahill/Split.js/blob/master/src/split.js#L175) where a and b both have sizes of NaN.

**Comment by nathancahill** [comment]
This is no longer supported, except for legacy code. Use percentages instead.
