### ISSUE TITLE
Bug when using Split in a RTL website

### ISSUE THREAD

**Issue by TpSr52** [nathancahill/Split.js#92]
When I RTL any page that uses Split.js with flexbox and I move the gutter towards the right, the gutter scrolls the left box towards left. When I try to move the gutter towards the farthest left, the gutter moves to the farthest right and gets stuck.

What can I do in order to fix it? Can anyone come up with a solution?

I am using the latest version of Split.js using the latest Yandex, But it happens also using chrome.

**Comment by nathancahill** [comment]
Do you have an example that shows this issue? I was not able to replicate.

**Comment by TpSr52** [comment]
I have added dir="RTL" into the HTML tag in the index.html (http://nathancahill.github.io/Split.js/). I saw this problem on Chrome 59, 60 and Yandex 17.7. In all the flexbox examples (The one under the text: "The actual size calculation falls back from calc() to support IE8, or can be configured to use flexbox." And the one under the text: "And with flexbox reverse:".

**Comment by nathancahill** [comment]
Great, thanks.

**Comment by TpSr52** [comment]
@nathancahill Do you have a temporary fix? or a solution?

**Comment by nathancahill** [comment]
Yes, you need to force `dir='ltr'` on the Split.js parent container. This is fixed in the example html page with this commit: d91182a

**Comment by asaf050** [comment]
@nathancahill setting the dir to 'ltr' is not a good solution, since it changes the content directions.
