### ISSUE TITLE
Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.

### ISSUE THREAD

**Issue by js321** [nathancahill/Split.js#93]
Hello,

I'm current using Split.js in the angularjs directive and works fine . But when i change the page of the single page application and come back to the previous page then I get the below error.

`
Error: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.`

Any help would be much appreciated. Thanks

**Comment by nathancahill** [comment]
It sounds like the Split.js instance is being initialized in the wrong part of the lifecycle of the single page app. Or it's not being destroyed when navigation occurs. Hard to say without seeing an example of the code causing the error, but it doesn't sound like an error with Split.js, so closing for now. Please comment if you have a minimal example.

**Comment by js321** [comment]
Thanks Nathan, managed to fix this by adding a timeout. This solved the issue.
