### ISSUE TITLE
Issue resizing a collapsed panel

### ISSUE THREAD

**Issue by Mottie** [nathancahill/Split.js#95]
I was messing around with the main demo API example and found an issue:

* Collapse First panel
* Collapse Second panel
* Attempt to resize the first panel.

What happens is the third panel "drops" out of the main container. Here is a animated screenshot showing the problem:

![](https://user-images.githubusercontent.com/136959/29192687-eb955ac6-7de7-11e7-937a-b2a2f5a067de.gif)

Reproduced in Chrome 60 &amp; Firefox 55 on a Windows 10 system.

**Comment by nathancahill** [comment]
I see, I was able to reproduce. The issue seems to come from the fact that `.collapse()` does not respect the min size, but dragging does (if you try to drag to panels 1 and 2 fully hidden, you won't be able to). Maybe `.collapse()` should respect min size to solve this.

**Comment by nathancahill** [comment]
Fixed in v1.5.0.
