### ISSUE TITLE
Gutter cursor on hover is lost after first drag

### ISSUE THREAD

**Issue by oanacrisan** [nathancahill/Split.js#99]
After the first drag of one of the split elements, the gutter no longer has that cursor on hover, I guess because of this line `self.gutter.style.cursor= ''` from the `stopDragging` function.

**Comment by oanacrisan** [comment]
Was using it in an angular 4 context, and needed to put a /deep/ selector to the `.gutter.gutter-horizontal` selector in my styling file.

**Comment by ilonashub** [comment]
I am having the same issues with React, only if I set the cursor in CSS then it worked :/

**Comment by jtlapp** [comment]
I'm also struggling with this in React. The following CSS is not sufficient:

```css
.gutter.gutter-horizontal {
  cursor: col-resize;
}
```

I can show the cursor on hover prior to the first drag by doing this:

```js
          gutterStyle={(dimension, gutterSize) => ({
            'flex-basis':  `${gutterSize}px`
            'cursor': 'col-resize'
          })}
```

After the first drag, the `col-resize` cursor disappears until I click on the gutter again.

**Comment by jtlapp** [comment]
I was able to resolve my issue by doing something messy:

```js
          gutterStyle={(dimension, gutterSize) => ({
            'flex-basis':  `${gutterSize}px`,
            'cursor': 'col-resize'
          })}
          onDragEnd={(sizes) => {
            let gutters = document.getElementsByClassName("gutter-horizontal");
            for (let i = 0; i < gutters.length; ++i) {
              gutters[i].classList.add("horizontalGutter");
            }
          }}
```

```css
.horizontalGutter {
  cursor: col-resize;
}
```

**Comment by bermanboris** [comment]
This behaviour is still broken and requires a hack
